[package]
name = "frontier"
version = "0.0.0"
edition = "2021"
description = "[WIP] A tool to reproduce distro installations."
license = "MIT"
authors = ["Peter Chaplin-Smith"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
