[package_manager]
name = "pacman"
args = ["--noconfirm"]

[pkgs]
install = [
	"aria2",
	"armcord",
	"auto-cpufreq",
	"base",
	"base-devel",
	"blueberry",
	"brightnessctl",
	"bspwm",
	"cinnamon",
	"dkms",
	"dnsmasq",
	"dunst",
	"ed",
	"efibootmgr",
	"exfat-utils",
	"flameshot",
	"flatpak",
	"fprintd",
	"fzf",
	"gef",
	"gimp",
	"git",
	"github-cli",
	"gitkraken",
	"gnome-keyring",
	"gnome-software",
	"gnome-terminal",
	"gst-plugin-pipewire",
	"hsetroot",
	"htop",
	"intel-ucode",
	"intellij-idea-ultimate-edition",
	"iwd",
	"jasper",
	"jdk-openjdk",
	"kdenlive",
	"kitty",
	"krita",
	"libpulse",
	"libreoffice-fresh",
	"librewolf-bin",
	"lightdm",
	"lightdm-gtk-greeter",
	"linux",
	"linux-firmware",
	"linux-headers",
	"linux-lts",
	"linux-lts-headers",
	"linux-wifi-hotspot",
	"lolcat-rs",
	"lxappearance",
	"metacity",
	"mold",
	"nano",
	"neofetch",
	"neovim",
	"net-tools",
	"network-manager-applet",
	"networkmanager",
	"nitrogen",
	"ntfs-3g",
	"nvidia-dkms",
	"obsidian",
	"p7zip",
	"pam-fprint-grosshack",
	"picom",
	"pipewire",
	"pipewire-alsa",
	"pipewire-jack",
	"pipewire-pulse",
	"polybar",
	"prospect-mail",
	"pulsemixer",
	"ripgrep",
	"rofi",
	"rsync",
	"rustup",
	"rxvt-unicode",
	"scrot",
	"smartmontools",
	"sof-firmware",
	"spotify",
	"sxhkd",
	"syncthing",
	"system-config-printer",
	"teams",
	"thefuck",
	"timeshift",
	"timg",
	"ufw",
	"unrar",
	"uv",
	"viewnior",
	"vim",
	"vlc",
	"vscodium",
	"wayclip",
	"wget",
	"whatsdesk-bin",
	"wireless_tools",
	"wireplumber",
	"xclip",
	"xdg-utils",
	"xorg-server",
	"xorg-xgamma",
	"xorg-xinit",
	"xorg-xinput",
	"xsel",
	"xsettingsd",
	"yay",
	"zoxide",
	"zsh",
]